artifacts_root: artifacts

data_ingestion:
  root_dir:artifacts/data_ingestion
  source_url: https://github.com/cmnepali/End-to-End-wine-quality-project/blob/main/wine.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzipdir: artifacts/data_ingestion